version: '3.8'

services:
  victorialogs:
    image: ${DOCKER_PROXY:-}victoriametrics/victoria-logs:v1.47.0
    command:
      - -retentionPeriod=2 # months
      - -defaultMsgValue=
    volumes:
      - ${DATA_PATH}/victorialogs:/victoria-logs-data
    networks:
      - internal
      - web
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.http.routers.victorialogs.entrypoints: 'websecure'
        traefik.http.routers.victorialogs.rule: Host(`${VICTORIALOGS_HOST:-victorialogs.local}`)
        traefik.http.services.victorialogs.loadbalancer.server.port: '9428'
        traefik.http.services.victorialogs.loadbalancer.server.scheme: 'http'

  victorialogs-exporter:
    image: ${DOCKER_PROXY:-}otel/opentelemetry-collector-contrib:0.147.0
    environment:
      TZ: 'Europe/Berlin'
    volumes:
      - ${DATA_PATH}/otel/victorialogs-exporter.yaml:/etc/otelcol-contrib/config.yaml
    networks:
      - internal
      - web

networks:
  internal:
    driver: overlay
  web:
    external: true
    name: traefik_web
