extensions:
  health_check:

receivers:
  prometheus/feedback:
    config:
      scrape_configs:
        - job_name: 'victoriatraces-exporter'
          scrape_interval: 10s
          static_configs:
            - targets: ['127.0.0.1:8888']

  kafka/traces:
    protocol_version: 2.1.0
    brokers:
      - {{ .Values.otel.kafka.bootstrapServers }}
    traces:
      topics:
        - otlp_spans
    group_id: victoriatraces-exporter
    message_marking:
      after: true
      on_error: false

exporters:
  otlp/feedback:
    endpoint: {{ .Values.otel.ingest.name }}:{{ .Values.otel.ingest.ports.otlpGrpc }}
    tls:
      insecure: true

  otlphttp/victoriatraces:
    traces_endpoint: {{ .Values.backendEndpoints.victoriatracesTraces }}
    sending_queue:
      enabled: true
      queue_size: 10000
      num_consumers: 10
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 30s
      max_elapsed_time: 0s

service:
  extensions: [health_check]
  pipelines:
    metrics/feedback:
      receivers: [prometheus/feedback]
      processors: []
      exporters: [otlp/feedback]
    traces:
      receivers: [kafka/traces]
      processors: []
      exporters: [otlphttp/victoriatraces]
