auth_enabled: false

server:
  http_listen_port: 3100

distributor:
  ring:
    kvstore:
      #store: memberlist
      store: inmemory

ingester:
  lifecycler:
    ring:
      kvstore:
        #store: memberlist
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2020-05-15
    store: boltdb-shipper
    object_store: s3
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
 boltdb_shipper:
   active_index_directory: /loki/index
   cache_location: /loki/index_cache
   shared_store: s3

 aws:
   s3: http://minioadmin:minioadmin@minio.:9000/loki
   s3forcepathstyle: true

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 7d
  retention_period: 60d

compactor:
  working_directory: /data/compactor
  shared_store: s3
  compaction_interval: 5m

#ruler:
#  alertmanager_url: http://alertmanager:9093

analytics:
  reporting_enabled: false
